-d D:\code\verilog\uart\gowin\fpga_project\impl\gwsynthesis\fpga_project.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst D:\code\verilog\uart\gowin\fpga_project\src\fpga_project.cst
-cfg D:\code\verilog\uart\gowin\fpga_project\impl\pnr\device.cfg
-sdc D:\code\verilog\uart\gowin\fpga_project\src\fpga_project.sdc
-bit
-tr
-ph
-timing
-cst_error
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
